export const projects = [
  {
    title: 'WhatsApp Clone',
    description: "Aplicativo para android feito em java com o objetivo de ser semelhante ao WhatsApp verdadeiro. O projeto não contém todos os recursos do WhatsApp, apenas os principais.",
    image: './images/image1.jpg',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/WhatsAppClone',
    visit: 'https://github.com/felipedalperio/WhatsAppClone',
    button:"Code",
    id: 0,
  },
  {
    title: 'Instagram Clone',
    description:"Projeto mobile (Android) com o intuito de parecer o verdadeiro Instagram, o aplicativo contém sistemas de postagem, aplicação de filtros em imagens e opções de curtir , seguir e comentar.",
    image: './images/image2.jpg',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/Instagram-Clone',
    visit: 'https://github.com/felipedalperio/Instagram-Clone',
    button:"Code",
    id: 1,
  },
  {
    title: 'Flappy Bird Clone',
    description: "Jogo ( android ) com o objetivo de ter as mesmas características do game Flappy Bird, o projeto foi realizado utilizando a biblioteca libGDX.",
      image: './images/image3.jpg',
      tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/Flappy-bird-clone',
    visit: 'https://github.com/felipedalperio/Flappy-bird-clone',
    button:"Code",
    id: 2,
  },
  {
    title: 'Quiz',
    description: "Questionário de perguntas e respostas com um contador (timer) para dispositivos android.",
    image: './images/image4.jpg',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/QuizzApplication',
    visit: 'https://github.com/felipedalperio/QuizzApplication',
    button:"Code",
    id: 3,
  },
  {
    title: 'Hotel para cachorro',
    description: "hotel para cachorro, no modelo MVC (Model, View, Controller), onde pessoas Jurídicas podem divulgar seus hoteis, e pessoas fisicas podem realizar uma simulação de preço.",
    image: './images/image5.jpg',
    tags: ['C#', 'Html', 'Css'],
    source: 'https://github.com/felipedalperio/hotel-para-cachorro',
    visit: 'https://github.com/felipedalperio/hotel-para-cachorro',
    button:"Code",
    id: 4,
  },
  {
    title: 'WhatsApp Web Clone',
    description: "Projeto Web para trocação de mensagens entre usuários. A autenticação é feita com o facebook utilizando o firebase.",
    image: './images/image6.png',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/whatsapp-web-clone',
    visit: 'https://github.com/felipedalperio/whatsapp-web-clone',
    button:"Code",
    id: 5,
  },
  {
    title: 'Olx Clone',
    description: "Projeto mobile (Android) com o intuito de parecer o verdadeiro OLX, o aplicativo contém sistemas de postagem e pesquisa com filtro de região.",
    image: './images/image7.jpg',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/olx_clone',
    visit: 'https://github.com/felipedalperio/olx_clone',
    button:"Code",
    id: 6,
  },
  {
    title: 'Game - Cara ou Coroa',
    description: "Simples projeto Android para trabalhar com números randômico e Fragments.",
    image: './images/image8.jpg',
    tags: ['Java'],
    source: 'https://github.com/felipedalperio/cara-coroa',
    visit: 'https://github.com/felipedalperio/cara-coroa',
    button:"Code",
    id: 7,
  },

  {
    title: 'Porta da sorte',
    description: "Um jogo para testar a sua sorte, onde quem joga deve tentar encontrar a porta premiada por eliminação. Podendo selecionar os níveis de dificuldade, através da movimentação do prêmio e a alteração do número de portas.",
    image: './images/image9.jpg',
    tags: ['JavaScript','React.js','Next.js'],
    source: 'https://github.com/felipedalperio/porta-premiada',
    visit: 'https://github.com/felipedalperio/porta-premiada',
    button:"Code",
    id: 8,
  },
  {
    title: 'Quiz Web',
    description: "Questionário de perguntas e respostas com (timer) e uma interface interativa.",
    image: './images/image10.jpg',
    tags: ['JavaScript','React.js','Next.js'],
    source: 'https://github.com/felipedalperio/quiz_web',
    visit: 'https://github.com/felipedalperio/quiz_web',
    button:"Code",
    id: 9,
  },
  {
    title: 'Confeitaria',
    description: "O WebSite Omagine é uma confeitaria de Bolachas e Cookies.",
    image: './images/image11.png',
    tags: ['JavaScript','React.js'],
    source: 'https://omaginebolachas.github.io/loja/',
    visit: 'https://omaginebolachas.github.io/loja/',
    button:"WebSite",
    id: 10,
  },
  {
    title: 'Blog',
    description: "Um Blog simples que contem um CRUD e Autenticação de usuário.",
    image: './images/imagem12.png',
    tags: ['Node.js','React.js','MongoDB'],
    source: 'https://github.com/felipedalperio',
    visit: 'https://github.com/felipedalperio',
    button:"Private",
    id: 11,
  }


  
];

export const TimeLineData = [
  { year: 2017, text: 'Iniciei minha jornada no mundo da programação.', },
  { year: 2018, text: 'Comecei a fazer faculdade de S.I na Universidade Positivo.', },
  { year: 2019, text: 'Foquei meus estudos em desenvolvimento mobile utilizando Java.', },
  { year: 2020, text: 'Desenvolvi projetos com base nos conhecimetos adiquiridos.', },
  { year: 2021, text: 'Iniciei meus estudos em desenvolvimento web utilizando React.', },
];