export const projects = [
  {
    title: 'Meu Blog',
    description: "Esse blog foi realizado em React.js (front-end) e Node.js(Back-end), O projeto possui um Crud completo, autenticação de usuário e mundança de tema (Dark - Light). ",
    image: './images/blog.webp',
    tags: ['React.js','MongoDb', 'Node.js', 'Redux', 'Styled-components'],
    source: 'https://lacodev.netlify.app',
    visit: 'https://lacodev.netlify.app',
    button:"Visitar",
    id: 1,
  },
  {
    title: 'Anote',
    description: "Anote é um aplicativo 3 em 1 (Metas, Rotinas e Bloco de notas). O projeto foi construido utilizando a linguagem nativa do Android (Java).",
    image: './images/anote.webp',
    tags: ['Java','SQlite'],
    source: 'https://play.google.com/store/apps/details?id=com.eren.trinuss',
    visit: 'https://play.google.com/store/apps/details?id=com.eren.trinuss',
    button:"PlayStore",
    id: 2,
  },
  {
    title: 'Alienn Agency',
    description: "O Alienn é uma agência que oferece serviços Freelancer para a criação de WebSites e Aplicativos móveis.",
    image: './images/alien.webp',
    tags: ['React','Context Api'],
    source: 'https://alienn.netlify.app',
    visit: 'https://alienn.netlify.app',
    button:"Visitar",
    id: 7,
  },
  {
    title: 'Confeitaria',
    description: "A Omagine é uma confeitaria de Bolachas e Cookies. O projeto é uma Lading Page com todas as informações da empresa, com o objetivo de aumentar as vendas.",
    image: './images/image11.webp',
    tags: ['JavaScript','React.js'],
    source: 'https://omaginebolachas.github.io/loja/',
    visit: 'https://omaginebolachas.github.io/loja/',
    button:"Visitar",
    id: 9,
  },
  {
    title: 'WhatsApp Clone',
    description: "Aplicativo para android feito em java com o objetivo de ser semelhante ao WhatsApp verdadeiro. O projeto não contém todos os recursos do WhatsApp, apenas os principais.",
    image: './images/whatsApp.webp',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/WhatsAppClone',
    visit: 'https://github.com/felipedalperio/WhatsAppClone',
    button:"Code",
    id: 3,
  },
  {
    title: 'WhatsApp Web Clone',
    description: "Projeto Web para trocação de mensagens entre usuários. A autenticação é feita com o facebook ou Google utilizando o firebase.",
    image: './images/whatsAppWeb.webp',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/WhatsAppReact',
    visit: 'https://github.com/felipedalperio/WhatsAppReact',
    button:"Code",
    id: 4,
  },
  {
    title: 'Instagram Clone',
    description:"Projeto mobile (Android) com o intuito de parecer o verdadeiro Instagram, o aplicativo contém sistemas de postagem, aplicação de filtros em imagens e opções de curtir , seguir e comentar.",
    image: './images/instagram.webp',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/Instagram-Clone',
    visit: 'https://github.com/felipedalperio/Instagram-Clone',
    button:"Code",
    id: 5,
  },
  {
    title: 'Flappy Bird Clone',
    description: "Jogo ( android ) com o objetivo de ter as mesmas características do game Flappy Bird, o projeto foi realizado utilizando a biblioteca libGDX.",
      image: './images/image3.webp',
      tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/Flappy-bird-clone',
    visit: 'https://github.com/felipedalperio/Flappy-bird-clone',
    button:"Code",
    id: 6,
  },
  {
    title: 'Vela Animada',
    description: "Essa animação simples foi realizada apenas com HTML & CSS utilizando keyframes.",
    image: './images/vela.gif',
    tags: ['HTML','CSS'],
    source: 'https://github.com/felipedalperio/Anima-o-Vela',
    visit: 'https://github.com/felipedalperio/Anima-o-Vela',
    button:"Code",
    id: 8,
  },
  {
    title: 'Olx Clone',
    description: "Projeto mobile (Android) com o intuito de parecer o verdadeiro OLX, o aplicativo contém sistemas de postagem e pesquisa com filtro de região.",
    image: './images/olx.webp',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/olx_clone',
    visit: 'https://github.com/felipedalperio/olx_clone',
    button:"Code",
    id: 10,
  },

  {
    title: 'Porta da sorte',
    description: "Um jogo para testar a sua sorte, onde quem joga deve tentar encontrar a porta premiada por eliminação. Podendo selecionar os níveis de dificuldade, através da movimentação do prêmio e a alteração do número de portas.",
    image: './images/image9.webp',
    tags: ['JavaScript','React.js','Next.js'],
    source: 'https://github.com/felipedalperio/porta-premiada',
    visit: 'https://github.com/felipedalperio/porta-premiada',
    button:"Code",
    id: 11,
  },
  {
    title: 'Quiz',
    description: "Questionário de perguntas e respostas com um contador (timer) para dispositivos android.",
    image: './images/image4.webp',
    tags: ['Java','firebase'],
    source: 'https://github.com/felipedalperio/QuizzApplication',
    visit: 'https://github.com/felipedalperio/QuizzApplication',
    button:"Code",
    id: 12,
  },
  {
    title: 'Quiz Web',
    description: "Questionário de perguntas e respostas com (timer) e uma interface interativa.",
    image: './images/quizz.webp',
    tags: ['JavaScript','React.js','Next.js'],
    source: 'https://github.com/felipedalperio/quiz_web',
    visit: 'https://github.com/felipedalperio/quiz_web',
    button:"Code",
    id: 13,
  },
  {
    title: 'Blog',
    description: "Um Blog simples que contem um CRUD e Autenticação de usuário.",
    image: './images/imagem13.webp',
    tags: ['Node.js','React.js','MongoDB'],
    source: 'https://github.com/felipedalperio',
    visit: 'https://github.com/felipedalperio',
    button:"Private",
    id: 14,
  },


  
];

export const TimeLineData = [
  { year: 2017, text: 'Iniciei minha jornada no mundo da programação.', },
  { year: 2018, text: 'Comecei a fazer faculdade de S.I na Universidade Positivo.', },
  { year: 2019, text: 'Foquei meus estudos em desenvolvimento mobile utilizando Java.', },
  { year: 2020, text: 'Desenvolvi projetos com base nos conhecimetos adiquiridos.', },
  { year: 2021, text: 'Iniciei meus estudos em desenvolvimento web utilizando React.', },
];